### ISSUE TITLE
mesh_edit_mesh.c and mesh_edit_mesh_fixup.c are named wrongly

### ISSUE THREAD

**Issue by ningyuansg** [recp/AssetKit#14]
https://github.com/recp/AssetKit/blob/35910c2c8e28a41c231acc17dd7d55e3b2791048/makefile.am#L145-L146

Should be mesh_edit_buff.c and mesh_edit_mesh_buff.c after [this refactor commit](https://github.com/recp/AssetKit/commit/2f6ead9bdbb8eebe4c81010ca1b7c6ee87a33bb8#diff-ecb4f2609a0632d06cad6f4e0e147b2f).

**Comment by recp** [comment]
I'll fix the build asap, feel free to open any other issues/pull request in the future.
