### ISSUE TITLE
`make install` overwrites /usr/include/string.h

### ISSUE THREAD

**Issue by emersion** [recp/AssetKit#19]
It seems like `include/ak/*.h` are directly copied to `/usr/include`.

**Comment by recp** [comment]
Hi @emersion 

Good catch, make file must be updated like [cglm](https://github.com/recp/cglm)'s build files. The current active branch is gltf-json.

I have written new json library (https://github.com/recp/json) to parse glTF and other json stuff. After that I've dropped old JSON parser and used the new one. It is almost finished, almost.

Also AssetKit is based on COLLADA and glTF. I'm trying to make it more simpler by dropping complexities that comes from COLLADA...

Any contribution is welcome 🤗

**Comment by recp** [comment]
@emersion this must be fixed at https://github.com/recp/AssetKit/commit/665645ec2ca6874fa6cf09bc408e4834cec905b5

Also AssetKit is provides CMake build files.

Thanks!

**Comment by emersion** [comment]
Nice, thanks!
