### ISSUE TITLE
How to compile this? getting error.

### ISSUE THREAD

**Issue by Blenux** [recp/AssetKit#25]
I keep getting this error and have git and python both installed and to PATH....

![Annotation 2020-05-18 003148](https://user-images.githubusercontent.com/25260650/82151451-09365880-989f-11ea-9b0b-e921bd2cd283.png)

note I am not a developer or coding person, I just want to test this addon ....

Thanks.

**Comment by recp** [comment]
Hello @Blenux 

AssetKit is a library not add-on of Blender yet. I, you or someone else may write add-on for Blender asap. 

After seen your issue, I'm trying to fix Windows build, I'll let you know here asap.

CMake integration (and maybe Blender add-on) will be available soon.

**Comment by recp** [comment]
@Blenux now Windows build is fixed.

**Comment by Blenux** [comment]
ah right I thought it was a addon, sadly I know nothing about turning this into a addon, hopefully someone does soon.

Thanks.

**Comment by recp** [comment]
Sorry for that, if someone don't do that, I'll try to write/make an add-on for Blender later, added to my TODOs.

We can close this issue I think :)
