### ISSUE TITLE
Can't build library on linux

### ISSUE THREAD

**Issue by eLeCtrOssSnake** [recp/AssetKit#27]
I am running Garuda Linux

I git clone the repository run cmake/automake as in the tutorial and i get compile errors after I run make.
```
Consolidate compiler generated dependencies of target ds
[  0%] Building C object deps/ds/CMakeFiles/ds.dir/src/util.c.o
/home/snake/Desktop/AssetKit/deps/ds/src/util.c: In function ‘ds_print_i64’:
/home/snake/Desktop/AssetKit/deps/ds/src/util.c:122:16: error: format ‘%llu’ expects argument of type ‘long long unsigned int’, but argument 2 has type ‘int64_t’ {aka ‘long int’} [-Werror=format=]
122 |   printf("\t%llu\n", *(int64_t *)key);
|             ~~~^     ~~~~~~~~~~~~~~~
|                |     |
|                |     int64_t {aka long int}
|                long long unsigned int
|             %lu
/home/snake/Desktop/AssetKit/deps/ds/src/util.c: In function ‘ds_print_ui64’:
/home/snake/Desktop/AssetKit/deps/ds/src/util.c:128:16: error: format ‘%llu’ expects argument of type ‘long long unsigned int’, but argument 2 has type ‘uint64_t’ {aka ‘long unsigned int’} [-Werror=format=]
128 |   printf("\t%llu\n", *(uint64_t *)key);
|             ~~~^     ~~~~~~~~~~~~~~~~
|                |     |
|                |     uint64_t {aka long unsigned int}
|                long long unsigned int
|             %lu
cc1: all warnings being treated as errors
make[2]: *** [deps/ds/CMakeFiles/ds.dir/build.make:104: deps/ds/CMakeFiles/ds.dir/src/util.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:672: deps/ds/CMakeFiles/ds.dir/all] Error 2
make: *** [Makefile:156: all] Error 2
```

If I try to hand fix these errors, a bunch of errors pop up, not just warning, but errors like AK_INLINE, AkFloat3 etc.

**Comment by eLeCtrOssSnake** [comment]
This what happends when i build using autotools
```
╭─snake@snake in repo: AssetKit on  master [!?] via △ v3.21.3 took 3s
╰─λ make
(CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/sh '/home/snake/Desktop/AssetKit/missing' autoheader)
rm -f stamp-h1
touch config.h.in
cd . && /bin/sh ./config.status config.h
config.status: creating config.h
make  all-am
make[1]: Entering directory '/home/snake/Desktop/AssetKit'
CC       src/assetkit.lo
In file included from src/../include/ak/assetkit.h:499,
from src/assetkit.c:17:
src/../include/ak/transform.h:33:3: error: size of array element is not a multiple of its alignment
33 |   AkFloat3     val[3];
|   ^~~~~~~~
In file included from src/io/gltf/common.h:23,
from src/io/gltf/gltf.h:20,
from src/assetkit.c:21:
src/io/gltf/../../tree.h:28:14: warning: ‘visibility’ attribute ignored on non-class types [-Wattributes]
28 |              xml_t  * __restrict xml);
|              ^~~~~
In file included from src/io/stl/stl.h:20,
from src/assetkit.c:23:
src/io/stl/common.h:42: warning: "SKIP_SPACES" redefined
42 | #define SKIP_SPACES                                                           \
| 
In file included from src/io/obj/obj.h:20,
from src/assetkit.c:22:
src/io/obj/common.h:81: note: this is the location of the previous definition
81 | #define SKIP_SPACES                                                           \
| 
make[1]: *** [makefile:1826: src/assetkit.lo] Error 1
make[1]: Leaving directory '/home/snake/Desktop/AssetKit'
make: *** [makefile:971: all] Error 2
```

**Comment by eLeCtrOssSnake** [comment]
I am building with gcc (GCC) 11.1.0

**Comment by recp** [comment]
Hello @eLeCtrOssSnake ,

I was working on morph targets, I'm updating the design; I'll check build file asap ;)

**Comment by eLeCtrOssSnake** [comment]
Thank you for your reply @recp. I am looking forward to use this library, because assimp didn't really work well, mostly because it's C++(as I am writing in C) and it is very slow at linking process when I am building my project.

I will be checking up on this quite frequently so you can ask me for help if needed.

**Comment by recp** [comment]
> I will be checking up on this quite frequently so you can ask me for help if needed.

I'll try to be fast as possible then 🤗

**AssetKit** will try to be fast as possible and try to support all formats' features as it can be with single interface. 

I'll try my best to complete unfinished parts, including build, I'll let you know here.

**Comment by eLeCtrOssSnake** [comment]
Any updates?

**Comment by recp** [comment]
> Okay, so the problem is that you assume if _MSC_VER is not defined that it's linux. That's what prevents it from building on windows under mingw because mingw obviously uses WinAPI(although there is msys but it's hacky, why if we already have WinAPI versions). So it would be better to check against linux define rather then msvc compiler version.
There's only one place where it warns about attribute being incorrect due to config is in ds_def_alc(). If you remove that attribute (and choose correct attributes ones for mingw and not dllimport) then it will build perfectly fine.

Thanks for that. I'll try to fix testing against msvc/mingw (`_MSC_VER`) later if this is the problem but any help would be appreciated ;) 

> Successfully builds on linux.

Great! Sice the library is new bugs may occour; I'll try to fix them (letting me know will make the process quicker I guess) and update documentation asap/time by time...

**Comment by recp** [comment]
Just created a PR: https://github.com/recp/AssetKit/pull/29

@eLeCtrOssSnake can you review and re-build the PR on mingw?

**Comment by eLeCtrOssSnake** [comment]
Ye, on it now @recp.

**Comment by recp** [comment]
I'm not sure if the attributes work on mingw too:

```C
#  define AK_ALIGN(X) __attribute((aligned(X)))
#  define AK_INLINE   static inline __attribute((always_inline))
```

it may expect msvc style instead of gcc I don't know.

**Comment by eLeCtrOssSnake** [comment]
I'll check it, ye it's kinda counter-intuitive.

**Comment by recp** [comment]
Many thanks

**Comment by eLeCtrOssSnake** [comment]
I am pretty confident to say that MinGW supports both __forceinline(defined as `extern __inline__ __attribute__((__always__inline__, __gnu_inline__))` and __attribute((aligned(X))), but I am pretty sure MinGW supports msvc style atributes as it has it's own defs as gcc style attributes.

**Comment by recp** [comment]
I'm confused about what to do, but it seems we can leave these attributes as they are. 

Did build succeded on mingw with that PR?

**Comment by recp** [comment]
Resolved at: https://github.com/recp/AssetKit/pull/29

@eLeCtrOssSnake many thanks...
